### ISSUE TITLE
Example is missing

### ISSUE THREAD

**Issue by chris-rock** [mintbridge/passport-ldap#4]
It would be great to see an example application. I think what is also missing is passport.serializeUser, passport.deserializeUser and this could be dependent of the custom ldap setup? Therefore the question is, what kind of ldap structure do you expect?

What is your proposed view?

**Comment by tedyoung** [comment]
Any update on examples?

**Comment by uxtx** [comment]
+1, would love to see an example.

**Comment by mentalbrew** [comment]
+1 on example as well

**Comment by JDvorak** [comment]
+1, example would be helpful.

**Comment by lomadurov** [comment]
+1

**Comment by stvnwrgs** [comment]
+1

**Comment by gastonconcilio** [comment]
+1

**Comment by blb78** [comment]
+1

**Comment by aaronbean** [comment]
+1

**Comment by oakley808** [comment]
+1

**Comment by EnzoMartin** [comment]
I've added an example file in my pull request (#9) for those still curious

**Comment by mintbridge** [comment]
@EnzoMartin78 kindly added an example in example.js
